<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <OutputType>Library</OutputType>
    <AssemblyName>JueMingR.Bootstrap</AssemblyName>
    <RootNamespace>JueMingR.Bootstrap</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
